config/routes.rb
Rails.application.routes.draw do
  resources :boards
  
  root 'home#index'
  
  get '/mypage'       =>  'mypages#index'
  get '/match'        =>  'matchs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.fetch(:board, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/matchs_controller.rb
class MatchsController < ApplicationController
    
    def index
    end
    
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matchs_helper.rb
module MatchsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/boards/_form.html.erb
<%= form_for(board) do |f| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<div class="content">
  <div class="container-fluid">
    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-20">
                <button type="button" class="btn btn-custom dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Settings </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item">Action</a>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item">Another action</a>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item">Something else</a>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item">Separated link</a>
                </div>
            </div>
            <h4 class="page-title">게시판 보드</h4>
        </div>
    </div>
    <!-- end page title end breadcrumb -->


    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
              <ul class="list-unstyled">
                <li>
                  <div class= "d-flex ">
                      <div class= "p-0 w-15">
                        <img class="pr-1" src = "https://www.bloter.net/wp-content/uploads/2017/06/%EA%B5%AC%EA%B8%80-765x430.png"
                         style="height: 60px; width: 90px;">
                      </div>
                      <div class= "flex-grow-1 flex-wrap ">
                        <div class = "p-0 flex-fill " >
                          <h5 class = "m-0"><strong>글 제목은 제한 없이 일단 길게 써본다.</strong></h5>
                        </div>
                        <div class= "p-0 " >
                          <small >카테고리</small>
                        </div>
                        <div class= "p-0 " >
                          <small>글 작성 날짜/작성자/추천 수</small>
                        </div>
                      </div>
                  </div>
                  <hr>
                </li>
                
                <li>
                  <div class= "d-flex ">
                      <div class= "p-0 w-15">
                        <img class="pr-1" src = "http://static.inven.co.kr/column/2014/05/21/news/i1568305431.jpg"
                         style="height: 60px; width: 90px;">
                      </div>
                      <div class= "flex-grow-1 flex-wrap ">
                        <div class = "p-0 flex-fill " >
                          <h5 class = "m-0"><strong>뿌애애애애애애애애애앵.</strong></h5>
                        </div>
                        <div class= "p-0 " >
                          <small >카테고리</small>
                        </div>
                        <div class= "p-0 " >
                          <small>글 작성 날짜/작성자/추천 수</small>
                        </div>
                      </div>
                  </div>
                  <hr>
                </li>
                
                <li>
                  <div class= "d-flex ">
                      <div class= "p-0 w-15">
                        <img class="pr-1" src = "https://cdn.namuwikiusercontent.com/s/ec96b7afb1f5fa0e3dc6144472683c6b2cfc72c91a5bcdfee98d2ae6e8d6ad189a4ad9f111b3a4e1d117bfa841499c7a661729bd8094ed91a39e27ec044a03c76e1c32eb5ba2e06847b1a652c980c5cd?e=1532360774&k=hZL8f0PM36GyAL_0k3Z-Jw"
                         style="height: 60px; width: 90px;">
                      </div>
                      <div class= "flex-grow-1 flex-wrap ">
                        <div class = "p-0 flex-fill " >
                          <h5 class = "m-0"><strong>니아ㅓ린야러잳 ㅑ</strong></h5>
                        </div>
                        <div class= "p-0 " >
                          <small >카테고리</small>
                        </div>
                        <div class= "p-0 " >
                          <small>글 작성 날짜/작성자/추천 수</small>
                        </div>
                      </div>
                  </div>
                  <hr>
                </li>
              </ul>
            </div> <!-- end card-box -->
        </div>
        <!-- end col -->
    </div>
    <!-- end row -->
  </div> <!-- end container -->
</div>

<% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
    console.log('script');
  </script>
<% end %>

app/views/boards/new.html.erb
<div class="content">
    <div class="container-fluid">
    <br><br><br><br>
        <div class="row">
            <div class="col-sm-12">
                <div class="card-box">
                    <form method="post">
                        <div>
                            <input type="text" class="p-1 form-control" placeholder="제목"></input>
                        </div>
                        <div class="pt-3">
                            <textarea id="elm1" name="area"></textarea>
                        </div>
                        <hr>
                        <div class="d-flex justify-content-end ">
                            <button type="submit" class = "btn btn-primary waves-effect waves-light"> 등록 </button>
                            <button type="submit" class = "btn btn-secondary waves-effect waves-light m-l-5"> 취소 </button>
                        </div>
                        
                        
                    </form>
                </div>
            </div><!-- end col -->
        </div>
        <!-- End row -->
    </div> <!-- container -->
</div>

<% content_for 'javascript_content' do%>
    <%= javascript_include_tag params[:controller]%>
    <script type="text/javascript">
            $(document).ready(function () {
                if($("#elm1").length > 0){
                    tinymce.init({
                        selector: "textarea#elm1",
                        theme: "modern",
                        height:300,
                        plugins: [
                            "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                            "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                            "save table contextmenu directionality emoticons template paste textcolor"
                        ],
                        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons",
                        style_formats: [
                            {title: 'Bold text', inline: 'b'},
                            {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                            {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                            {title: 'Example 1', inline: 'span', classes: 'example1'},
                            {title: 'Example 2', inline: 'span', classes: 'example2'},
                            {title: 'Table styles'},
                            {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
                        ]
                    });
                }
            });
        </script>
<% end %>

app/views/boards/show.html.erb
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8">
                <div class="bg-picture card-box">
                    <div class="profile-info-name">
                        <div class="profile-info-detail">
                            <!--제목바-->
                            <div>
                                <!--왼쪽-->
                                <div class="d-flex flex-column">
                                    <div class="d-flex justify-content-between">
                                        <h4 class="m-0 p-0">킹갓제너럴충무공엠페러마제스티우주존잘남이다.</h4>
                                        <div class="dropdown pull-right">
                                            <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                                                <i class="mdi mdi-dots-vertical"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <!-- item-->
                                                <a href="javascript:void(0);" class="dropdown-item">Edit</a>
                                                <!-- item-->
                                                <a href="javascript:void(0);" class="dropdown-item">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    <div class="d-flex justify-content-between">
                                        <div class="pt-1 comment " style="width: 50%;">
                                            <img src="<%= asset_path 'users/avatar-7.jpg' %>" alt="" class="m-1 comment-avatar">
                                            <div class="ml-1 ">
                                                <p class="text-muted "><i>모두가아는남자신의민</i></p>
                                            </div>
                                        </div>
                                        <div class= "d-flex align-items-end flex-column" style="width: 50%;">
                                            <small class="pt-2">2088.01.15</small>
                                            <small class="p-0">
                                                    조회수 <strong>500</strong>
                                                    추천수 <strong>500</strong>
                                                </small>
                                        </div>
                                        </div>
                                    
                                </div>
                            </div>
                            <hr>
                            
                            <!--내용 영역-->
                            <div>
                                <p> 임마! 어?! 내가 누군지 알어! 어?! 내가! 마! 니 서장이랑! 어! 밥도 묵고! 술도 묵고! 다했어! 마! </p>
                            <br><br><br><br><br><br><br><br><br>
                            </div>
                            
                            <!--하위 영역-->
                            <div class="d-flex justify-content-center m-t-20 pr-0 mr-0">
                                <div class="d-flex ">
                                    <a href="#"  class="mr-2 align-self-center text-primary badge badge-light" style="border-radius: 100%; ">
                                        <i class="fa fa-thumbs-o-up " style="font-size: 22px"></i>
                                    </a>
                                    <h5 class="align-self-center mr-0">500</h5>
                                </div>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                </div>
                <!--/ meta -->



                <form method="post" class="card-box">
                    <span class="input-icon icon-right">
                        <textarea rows="2" class="form-control" placeholder="Post a new message"></textarea>
                    </span>
                    <div class="p-t-10 pull-right">
                        <a class="btn btn-sm btn-primary waves-effect waves-light">Send</a>
                    </div>
                    <br><br>
                </form>
                
                <!--comment list-->
                <div class="card-box">
                    <!--comment01-->
                    <div class="comment">
                        <img src="<%= asset_path 'users/avatar-1.jpg' %>" alt="" class="comment-avatar">
                        <div class="comment-body">
                            <div class="comment-text">
                                <div class="comment-header">
                                    <a href="#" title="">Adam Jansen</a><span>about 2 minuts ago</span>
                                </div>
                                Story based around the idea of time lapse, animation to post soon!
                            </div>
                        </div>
                    </div>
                    
                    <!--comment02-->
                    <div class="comment">
                        <img src="<%= asset_path 'users/avatar-1.jpg' %>" alt="" class="comment-avatar">
                        <div class="comment-body">
                            <div class="comment-text">
                                <div class="comment-header">
                                    <a href="#" title="">Kim Ryder</a><span>about 4 hours ago</span>
                                </div>
                                i'm in the middle of a timelapse animation myself! (Very different
                                though.) Awesome stuff.
                            </div>
                        </div>
                    </div>
                    
                    <!--comment02-->
                    <div class="comment">
                        <img src="<%= asset_path 'users/avatar-7.jpg' %>" alt="" class="comment-avatar m-0">
                        <div class="comment-body">
                            <div class="comment-text">
                                <div class="comment-header">
                                    <a href="#" title="">Nicolai Larson</a><span>10 hours ago</span>
                                </div>
                                the parallax is a little odd but O.o that house build is awesome!!
                            </div>
                        </div>
                    </div>

                    <div class="m-t-30 text-center">
                        <a href="" class="btn btn-default waves-effect waves-light btn-sm">Load More...</a>
                    </div>
                </div>


            </div>

            <div class="col-sm-4">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30">베스트 인기 글</h4>

                    <ul class="list-group m-b-0 user-list">
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="comment">
                                    <img src="https://www.bloter.net/wp-content/uploads/2017/06/%EA%B5%AC%EA%B8%80-765x430.png" alt="" class="comment-avatar">
                                </div>
                                <div class="user-desc">
                                    <span class="name">글 제목은 제한 없이 일단 길게 써본다.</span>
                                    <span class="desc">카테고리</span>
                                </div>
                            </a>
                        </li>

                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="comment">
                                    <img src="http://static.inven.co.kr/column/2014/05/21/news/i1568305431.jpg" alt="" class="comment-avatar">
                                </div>
                                <div class="user-desc">
                                    <span class="name">뿌애애애애애애애애애앵.</span>
                                    <span class="desc">카테고리</span>
                                </div>
                            </a>
                        </li>

                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="comment">
                                    <img src="https://cdn.namuwikiusercontent.com/s/ec96b7afb1f5fa0e3dc6144472683c6b2cfc72c91a5bcdfee98d2ae6e8d6ad189a4ad9f111b3a4e1d117bfa841499c7a661729bd8094ed91a39e27ec044a03c76e1c32eb5ba2e06847b1a652c980c5cd?e=1532360774&k=hZL8f0PM36GyAL_0k3Z-Jw" alt="" class="comment-avatar">
                                </div>
                                <div class="user-desc">
                                    <span class="name">니아ㅓ린야러잳 ㅑ</span>
                                    <span class="desc m-b-0">카테고리</span>
                                </div>
                            </a>
                        </li>

                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="comment">
                                    <img src="<%= asset_path 'users/avatar-6.jpg' %>" alt="" class="comment-avatar">
                                </div>
                                <div class="user-desc">
                                    <span class="name">Michael Zenaty</span>
                                    <span class="desc">Programmer</span>
                                </div>
                            </a>
                        </li>

                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="comment">
                                    <img src="<%= asset_path 'users/avatar-1.jpg' %>" alt="" class="comment-avatar">
                                </div>
                                <div class="user-desc">
                                    <span class="name">Mat Helme</span>
                                    <span class="desc">Manager</span>
                                </div>
                            </a>
                        </li>
                        
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="comment">
                                    <img src="<%= asset_path 'users/avatar-3.jpg' %>" alt="" class="comment-avatar">
                                </div>
                                <div class="user-desc">
                                    <span class="name">Mat Helme</span>
                                    <span class="desc">Manager</span>
                                </div>
                            </a>
                        </li>
                        
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="comment">
                                    <img src="<%= asset_path 'users/avatar-1.jpg' %>" alt="" class="comment-avatar">
                                </div>
                                <div class="user-desc">
                                    <span class="name">Mat Helme</span>
                                    <span class="desc">Manager</span>
                                </div>
                            </a>
                        </li>
                        
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="comment">
                                    <img src="<%= asset_path 'users/avatar-2.jpg' %>" alt="" class="comment-avatar">
                                </div>
                                <div class="user-desc">
                                    <span class="name">Mat Helme</span>
                                    <span class="desc">Manager</span>
                                </div>
                            </a>
                        </li>
                        
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="comment">
                                    <img src="<%= asset_path 'users/avatar-3.jpg' %>" alt="" class="comment-avatar">
                                </div>
                                <div class="user-desc">
                                    <span class="name">Mat Helme</span>
                                    <span class="desc">Manager</span>
                                </div>
                            </a>
                        </li>
                        
                        
                    </ul>
                </div>
            </div>
        </div>
    </div> <!-- container -->
</div> <!-- content -->
                
<% content_for 'javascript_content' do %>
    <%= javascript_include_tag params[:controller] %>
    <script>
    console.log('script');
    </script>
<% end %>

app/views/home/_custombox.html.erb
<div id="custom-modal" class="modal-demo" style="">
                <button type="button" class="close" onclick="Custombox.close();">
                    <span>×</span><span class="sr-only">Close</span>
                </button>
                <h4 class="custom-modal-title">게임 연동</h4>
                <div class="custom-modal-text text-left">
                    <form role="form" method="get">
                        <div class="form-group">
                            <label for="game">Game</label>
                            <select name="gamename" class="form-control">
                              <option value="lol">롤</option>
                              <option value="ow">오버워치</option>
                              <option value="bg">배틀그라운드</option>
                            </select>
                        </div>
                         <div class="form-group">
                            <label for="name">ID</label>
                            <input name="gameid" type="text" class="form-control" id="name" placeholder="게임 아이디를 입력하세요">
                        </div>
                        <button type="submit" class="btn btn-success waves-effect waves-light">Save</button>
                        <button type="button" class="btn btn-danger waves-effect waves-light m-l-5">Cancel</button>
                    </form>
                </div>
            </div>

app/views/home/index.html.erb
<!-- Start content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <!---->
    		<div class="card-box d-flex align-items-start flex-column " style="height: 500px; width: 500px;" >
    		  <div style="height: 60%;">
    		    <%= render 'shared/cardlist' %>
    		  </div>
    		  <div class="w-100 d-flex flex-column " style="height: 40%;">
    		    <div class="h-75">
    		      <h4>Game Title</h4>
    		      <p >현재 1005165명이 이 게임에서 팀원을 찾는 중입니다.</p>
    		    </div>
    		    
    		    <div class="d-flex h-25 align-items-end justify-content-end">
    		      
    		      <a href="/" class="popp badge badge-light align-items-center" 
    		        data-container="body" data-trigger="hover" data-placement="top" 
    		        data-content="당신의 멘토를 찾아드립니다." >
    		        <i class=" mdi mdi-account-convert text-primary"  style="font-size: 20px;"></i>
    		      </a>
    		      &nbsp&nbsp
    		      <a href="/match" class="popp badge badge-light align-items-center"
    		        data-container="body" data-trigger="hover" data-placement="top" 
    		        data-content="당신의 팀원을 찾아드립니다." >
    		        <i class="ti-game text-primary" style="font-size: 20px;"></i>
    		      </a>
    		      
    		    </div>
    		  </div>
      </div><!-- end col -->
      
    </div>
  </div> <!-- container -->
</div> <!-- content -->


<!-- Javascript contents -->
<% content_for 'javascript_content' do %>
<%= javascript_include_tag params[:controller] %>
<script>
$('.popp').popover();
</script>
<% end %>

app/views/home/mypage.html.erb
<!-- Start content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
        <div class="col-xl-4 col-md-6"> 
            <div class="card-box d-flex justify-content-start">
                <div class="d-flex align-items-center flex-column ">
                    <img src="<%= asset_path 'users/avatar-1.jpg' %>" >
                    <button class="form-control btn"> 프로필 수정 </button>
                </div>
                    
                <div class="pl-4 flex-column">
                    <h5 class="mt-0 mb-1">User Name</h5>
                    <p >킹갓제너럴충무공마제스티우주미남</p>
                    
                    <h5 class="mb-1">Email</h5>
                    <p>갓미남@미남.com</p>
                    
                    <h5 class="mb-1">Index</h5>
                    <p>Index</p>
                </div>
            </div>
        </div>
        
        <div class="col-xl-4 col-md-6">
            <div class="card-box taskboard-box">
                <ul class="list-unstyled task-list">
                    <li class="mb-2">
                        <div class="kanban-box">
                            <div class="kanban-detail ml-2 p-1">
                                <a href="#" class="badge badge-light text-primary pull-right">X</a>
                                <h4 class="mb-1">로오오옹ㄹ</h4>
                                <img class="thumb-sm rounded-circle"  src="<%= asset_path 'users/avatar-1.jpg' %>" >
                            </div>
                        </div>
                    </li>
                    <li class="mb-2">
                        <div class="kanban-box">
                            <div class="kanban-detail ml-2 p-1">
                                <a href="#" class="badge badge-light text-primary  pull-right">X</a>
                                <h4 class="mb-1">오버워치</h4>
                                <img class="thumb-sm rounded-circle"  src="<%= asset_path 'users/avatar-1.jpg' %>" >
                            </div>
                        </div>
                    </li>
                    <li class="mb-2">
                        <div class="kanban-box">
                            <div class="kanban-detail ml-2 p-1">
                                <a href="#" class="badge badge-light text-primary  pull-right">X</a>
                                <h4 class="mb-1">배애앵그</h4>
                                <img class="thumb-sm rounded-circle"  src="<%= asset_path 'users/avatar-1.jpg' %>" >
                            </div>
                        </div>
                    </li>
                    <li class="">
                        <button href="#custom-modal" class="btn btn-primary form-control"
                        data-animation="fadein" data-plugin="custommodal" data-overlayspeed="200" 
                        data-overlaycolor="#36404a">
                            추가
                        </button>
                    </li>
                </ul>
            </div>  
        </div>
        
        

    </div>
  </div> <!-- container -->
</div> <!-- content -->

<%=render 'custombox' %>

<!-- Javascript contents -->
<% content_for 'javascript_content' do %>
<%= javascript_include_tag params[:controller] %>
<script>
$('.popp').popover();
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TempApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <div id="wrapper">
      <%= render 'shared/topbar' %>
      <%= render 'shared/leftsidemenu' %>
      
      <div class="content-page">
        <%= yield %>
        <!--<footer class="footer text-right">-->
        <!--    2016 - 2018 © Adminto. Coderthemes.com-->
        <!--</footer>-->
      </div>
      <%= render 'shared/siderightbar' %>
    </div>
    
    <%= yield 'javascript_content' %>
  </body>
</html>